//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIL.LCModel.DomainServices {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ScrResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ScrResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SIL.LCModel.DomainServices.ScrResources", typeof(ScrResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic.
        /// </summary>
        internal static string Basic {
            get {
                return ResourceManager.GetString("Basic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chapter number out of range.
        /// </summary>
        internal static string Chapter_number_out_of_range {
            get {
                return ResourceManager.GetString("Chapter_number_out_of_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chapter out of order; expected chapter {0}.
        /// </summary>
        internal static string Chapter_out_of_order__expected_chapter__0_ {
            get {
                return ResourceManager.GetString("Chapter_out_of_order__expected_chapter__0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate chapter number.
        /// </summary>
        internal static string Duplicate_chapter_number {
            get {
                return ResourceManager.GetString("Duplicate_chapter_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate verse number.
        /// </summary>
        internal static string Duplicate_verse_number {
            get {
                return ResourceManager.GetString("Duplicate_verse_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate verse numbers.
        /// </summary>
        internal static string Duplicate_verse_numbers {
            get {
                return ResourceManager.GetString("Duplicate_verse_numbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected.
        /// </summary>
        internal static string Expected {
            get {
                return ResourceManager.GetString("Expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heading should begin with a capital letter.
        /// </summary>
        internal static string Heading_should_begin_with_a_capital_letter {
            get {
                return ResourceManager.GetString("Heading_should_begin_with_a_capital_letter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid chapter number.
        /// </summary>
        internal static string Invalid_chapter_number {
            get {
                return ResourceManager.GetString("Invalid_chapter_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid or unknown character.
        /// </summary>
        internal static string Invalid_or_unknown_character {
            get {
                return ResourceManager.GetString("Invalid_or_unknown_character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid or unknown character diacritic combination.
        /// </summary>
        internal static string Invalid_or_unknown_character_diacritic_combination {
            get {
                return ResourceManager.GetString("Invalid_or_unknown_character_diacritic_combination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid punctuation pattern.
        /// </summary>
        internal static string Invalid_punctuation_pattern {
            get {
                return ResourceManager.GetString("Invalid_punctuation_pattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid verse number.
        /// </summary>
        internal static string Invalid_verse_number {
            get {
                return ResourceManager.GetString("Invalid_verse_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Introduction.
        /// </summary>
        internal static string kstidBookIntroduction {
            get {
                return ResourceManager.GetString("kstidBookIntroduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genesis.
        /// </summary>
        internal static string kstidBookName1 {
            get {
                return ResourceManager.GetString("kstidBookName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 Samuel.
        /// </summary>
        internal static string kstidBookName10 {
            get {
                return ResourceManager.GetString("kstidBookName10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Kings.
        /// </summary>
        internal static string kstidBookName11 {
            get {
                return ResourceManager.GetString("kstidBookName11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 Kings.
        /// </summary>
        internal static string kstidBookName12 {
            get {
                return ResourceManager.GetString("kstidBookName12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Chronicles.
        /// </summary>
        internal static string kstidBookName13 {
            get {
                return ResourceManager.GetString("kstidBookName13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 Chronicles.
        /// </summary>
        internal static string kstidBookName14 {
            get {
                return ResourceManager.GetString("kstidBookName14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ezra.
        /// </summary>
        internal static string kstidBookName15 {
            get {
                return ResourceManager.GetString("kstidBookName15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nehemiah.
        /// </summary>
        internal static string kstidBookName16 {
            get {
                return ResourceManager.GetString("kstidBookName16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esther.
        /// </summary>
        internal static string kstidBookName17 {
            get {
                return ResourceManager.GetString("kstidBookName17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job.
        /// </summary>
        internal static string kstidBookName18 {
            get {
                return ResourceManager.GetString("kstidBookName18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Psalms.
        /// </summary>
        internal static string kstidBookName19 {
            get {
                return ResourceManager.GetString("kstidBookName19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exodus.
        /// </summary>
        internal static string kstidBookName2 {
            get {
                return ResourceManager.GetString("kstidBookName2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proverbs.
        /// </summary>
        internal static string kstidBookName20 {
            get {
                return ResourceManager.GetString("kstidBookName20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ecclesiastes.
        /// </summary>
        internal static string kstidBookName21 {
            get {
                return ResourceManager.GetString("kstidBookName21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song of Solomon.
        /// </summary>
        internal static string kstidBookName22 {
            get {
                return ResourceManager.GetString("kstidBookName22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isaiah.
        /// </summary>
        internal static string kstidBookName23 {
            get {
                return ResourceManager.GetString("kstidBookName23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jeremiah.
        /// </summary>
        internal static string kstidBookName24 {
            get {
                return ResourceManager.GetString("kstidBookName24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lamentations.
        /// </summary>
        internal static string kstidBookName25 {
            get {
                return ResourceManager.GetString("kstidBookName25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ezekiel.
        /// </summary>
        internal static string kstidBookName26 {
            get {
                return ResourceManager.GetString("kstidBookName26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daniel.
        /// </summary>
        internal static string kstidBookName27 {
            get {
                return ResourceManager.GetString("kstidBookName27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hosea.
        /// </summary>
        internal static string kstidBookName28 {
            get {
                return ResourceManager.GetString("kstidBookName28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joel.
        /// </summary>
        internal static string kstidBookName29 {
            get {
                return ResourceManager.GetString("kstidBookName29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leviticus.
        /// </summary>
        internal static string kstidBookName3 {
            get {
                return ResourceManager.GetString("kstidBookName3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amos.
        /// </summary>
        internal static string kstidBookName30 {
            get {
                return ResourceManager.GetString("kstidBookName30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obadiah.
        /// </summary>
        internal static string kstidBookName31 {
            get {
                return ResourceManager.GetString("kstidBookName31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jonah.
        /// </summary>
        internal static string kstidBookName32 {
            get {
                return ResourceManager.GetString("kstidBookName32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Micah.
        /// </summary>
        internal static string kstidBookName33 {
            get {
                return ResourceManager.GetString("kstidBookName33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nahum.
        /// </summary>
        internal static string kstidBookName34 {
            get {
                return ResourceManager.GetString("kstidBookName34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Habakkuk.
        /// </summary>
        internal static string kstidBookName35 {
            get {
                return ResourceManager.GetString("kstidBookName35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zephaniah.
        /// </summary>
        internal static string kstidBookName36 {
            get {
                return ResourceManager.GetString("kstidBookName36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haggai.
        /// </summary>
        internal static string kstidBookName37 {
            get {
                return ResourceManager.GetString("kstidBookName37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zechariah.
        /// </summary>
        internal static string kstidBookName38 {
            get {
                return ResourceManager.GetString("kstidBookName38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malachi.
        /// </summary>
        internal static string kstidBookName39 {
            get {
                return ResourceManager.GetString("kstidBookName39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbers.
        /// </summary>
        internal static string kstidBookName4 {
            get {
                return ResourceManager.GetString("kstidBookName4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matthew.
        /// </summary>
        internal static string kstidBookName40 {
            get {
                return ResourceManager.GetString("kstidBookName40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark.
        /// </summary>
        internal static string kstidBookName41 {
            get {
                return ResourceManager.GetString("kstidBookName41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luke.
        /// </summary>
        internal static string kstidBookName42 {
            get {
                return ResourceManager.GetString("kstidBookName42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to John.
        /// </summary>
        internal static string kstidBookName43 {
            get {
                return ResourceManager.GetString("kstidBookName43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acts.
        /// </summary>
        internal static string kstidBookName44 {
            get {
                return ResourceManager.GetString("kstidBookName44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Romans.
        /// </summary>
        internal static string kstidBookName45 {
            get {
                return ResourceManager.GetString("kstidBookName45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Corinthians.
        /// </summary>
        internal static string kstidBookName46 {
            get {
                return ResourceManager.GetString("kstidBookName46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 Corinthians.
        /// </summary>
        internal static string kstidBookName47 {
            get {
                return ResourceManager.GetString("kstidBookName47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Galatians.
        /// </summary>
        internal static string kstidBookName48 {
            get {
                return ResourceManager.GetString("kstidBookName48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ephesians.
        /// </summary>
        internal static string kstidBookName49 {
            get {
                return ResourceManager.GetString("kstidBookName49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deuteronomy.
        /// </summary>
        internal static string kstidBookName5 {
            get {
                return ResourceManager.GetString("kstidBookName5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Philippians.
        /// </summary>
        internal static string kstidBookName50 {
            get {
                return ResourceManager.GetString("kstidBookName50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colossians.
        /// </summary>
        internal static string kstidBookName51 {
            get {
                return ResourceManager.GetString("kstidBookName51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Thessalonians.
        /// </summary>
        internal static string kstidBookName52 {
            get {
                return ResourceManager.GetString("kstidBookName52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 Thessalonians.
        /// </summary>
        internal static string kstidBookName53 {
            get {
                return ResourceManager.GetString("kstidBookName53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Timothy.
        /// </summary>
        internal static string kstidBookName54 {
            get {
                return ResourceManager.GetString("kstidBookName54", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 Timothy.
        /// </summary>
        internal static string kstidBookName55 {
            get {
                return ResourceManager.GetString("kstidBookName55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titus.
        /// </summary>
        internal static string kstidBookName56 {
            get {
                return ResourceManager.GetString("kstidBookName56", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Philemon.
        /// </summary>
        internal static string kstidBookName57 {
            get {
                return ResourceManager.GetString("kstidBookName57", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hebrews.
        /// </summary>
        internal static string kstidBookName58 {
            get {
                return ResourceManager.GetString("kstidBookName58", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to James.
        /// </summary>
        internal static string kstidBookName59 {
            get {
                return ResourceManager.GetString("kstidBookName59", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joshua.
        /// </summary>
        internal static string kstidBookName6 {
            get {
                return ResourceManager.GetString("kstidBookName6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Peter.
        /// </summary>
        internal static string kstidBookName60 {
            get {
                return ResourceManager.GetString("kstidBookName60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 Peter.
        /// </summary>
        internal static string kstidBookName61 {
            get {
                return ResourceManager.GetString("kstidBookName61", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 John.
        /// </summary>
        internal static string kstidBookName62 {
            get {
                return ResourceManager.GetString("kstidBookName62", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 John.
        /// </summary>
        internal static string kstidBookName63 {
            get {
                return ResourceManager.GetString("kstidBookName63", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 John.
        /// </summary>
        internal static string kstidBookName64 {
            get {
                return ResourceManager.GetString("kstidBookName64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jude.
        /// </summary>
        internal static string kstidBookName65 {
            get {
                return ResourceManager.GetString("kstidBookName65", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revelation.
        /// </summary>
        internal static string kstidBookName66 {
            get {
                return ResourceManager.GetString("kstidBookName66", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Judges.
        /// </summary>
        internal static string kstidBookName7 {
            get {
                return ResourceManager.GetString("kstidBookName7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruth.
        /// </summary>
        internal static string kstidBookName8 {
            get {
                return ResourceManager.GetString("kstidBookName8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Samuel.
        /// </summary>
        internal static string kstidBookName9 {
            get {
                return ResourceManager.GetString("kstidBookName9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checks for potentially invalid characters..
        /// </summary>
        internal static string kstidDescription_6558A579B9C44EFD8728F994D0561293 {
            get {
                return ResourceManager.GetString("kstidDescription_6558A579B9C44EFD8728F994D0561293", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checks for repeated words..
        /// </summary>
        internal static string kstidDescription_72ABB400F274449892C577E99C90F75B {
            get {
                return ResourceManager.GetString("kstidDescription_72ABB400F274449892C577E99C90F75B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checks for potential inconsistencies in capitalization..
        /// </summary>
        internal static string kstidDescription_BABCB400F274449892C577E99C90F75B {
            get {
                return ResourceManager.GetString("kstidDescription_BABCB400F274449892C577E99C90F75B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checks for words with a potentially invalid mix of uppercase and lowercase letters..
        /// </summary>
        internal static string kstidDescription_BABCB400F274449892C577E99C90F75D {
            get {
                return ResourceManager.GetString("kstidDescription_BABCB400F274449892C577E99C90F75D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checks for potential inconsistencies in the use of punctuation..
        /// </summary>
        internal static string kstidDescription_DCC8D4D213B246E48FB329C166D189EA {
            get {
                return ResourceManager.GetString("kstidDescription_DCC8D4D213B246E48FB329C166D189EA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checks for unmatched parentheses or other punctuation that normally occurs in pairs..
        /// </summary>
        internal static string kstidDescription_DDCCB400F274449892C577E99C90F75B {
            get {
                return ResourceManager.GetString("kstidDescription_DDCCB400F274449892C577E99C90F75B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checks for potential inconsistencies in the markup of quotations..
        /// </summary>
        internal static string kstidDescription_DDCCB400F274449892C577E99C90F75C {
            get {
                return ResourceManager.GetString("kstidDescription_DDCCB400F274449892C577E99C90F75C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checks for potential inconsistencies in chapter and verse numbers..
        /// </summary>
        internal static string kstidDescription_F17A054BD21E4298A1A50D79C4AF6F0F {
            get {
                return ResourceManager.GetString("kstidDescription_F17A054BD21E4298A1A50D79C4AF6F0F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum number of {0} errors exceeded..
        /// </summary>
        internal static string kstidExceededMaxNumberIdenticalChecks {
            get {
                return ResourceManager.GetString("kstidExceededMaxNumberIdenticalChecks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}
        ///This file will be removed from the import project&quot;.
        /// </summary>
        internal static string kstidImportBadFile {
            get {
                return ResourceManager.GetString("kstidImportBadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Characters.
        /// </summary>
        internal static string kstidName_6558A579B9C44EFD8728F994D0561293 {
            get {
                return ResourceManager.GetString("kstidName_6558A579B9C44EFD8728F994D0561293", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeated Words.
        /// </summary>
        internal static string kstidName_72ABB400F274449892C577E99C90F75B {
            get {
                return ResourceManager.GetString("kstidName_72ABB400F274449892C577E99C90F75B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capitalization.
        /// </summary>
        internal static string kstidName_BABCB400F274449892C577E99C90F75B {
            get {
                return ResourceManager.GetString("kstidName_BABCB400F274449892C577E99C90F75B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mixed Capitalization.
        /// </summary>
        internal static string kstidName_BABCB400F274449892C577E99C90F75D {
            get {
                return ResourceManager.GetString("kstidName_BABCB400F274449892C577E99C90F75D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punctuation Patterns.
        /// </summary>
        internal static string kstidName_DCC8D4D213B246E48FB329C166D189EA {
            get {
                return ResourceManager.GetString("kstidName_DCC8D4D213B246E48FB329C166D189EA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matching Punctuation Pairs.
        /// </summary>
        internal static string kstidName_DDCCB400F274449892C577E99C90F75B {
            get {
                return ResourceManager.GetString("kstidName_DDCCB400F274449892C577E99C90F75B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quotation Marks.
        /// </summary>
        internal static string kstidName_DDCCB400F274449892C577E99C90F75C {
            get {
                return ResourceManager.GetString("kstidName_DDCCB400F274449892C577E99C90F75C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chapter and Verse Numbers.
        /// </summary>
        internal static string kstidName_F17A054BD21E4298A1A50D79C4AF6F0F {
            get {
                return ResourceManager.GetString("kstidName_F17A054BD21E4298A1A50D79C4AF6F0F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Paratext project selected for Back Translation is already in use. The projects must be unique..
        /// </summary>
        internal static string kstidPtBtAlreadyUsed {
            get {
                return ResourceManager.GetString("kstidPtBtAlreadyUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Paratext project selected for notes is already in use. The projects must be unique..
        /// </summary>
        internal static string kstidPtNotesAlreadyUsed {
            get {
                return ResourceManager.GetString("kstidPtNotesAlreadyUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Paratext project selected for Scripture is already in use. The projects must be unique..
        /// </summary>
        internal static string kstidPtScrAlreadyUsed {
            get {
                return ResourceManager.GetString("kstidPtScrAlreadyUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level {0} quote closed.
        /// </summary>
        internal static string Level__0__quote_closed {
            get {
                return ResourceManager.GetString("Level__0__quote_closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level {0} quote continuer.
        /// </summary>
        internal static string Level__0__quote_continuer {
            get {
                return ResourceManager.GetString("Level__0__quote_continuer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level {0} quote opened.
        /// </summary>
        internal static string Level__0__quote_opened {
            get {
                return ResourceManager.GetString("Level__0__quote_opened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing chapter number {0}.
        /// </summary>
        internal static string Missing_chapter_number__0_ {
            get {
                return ResourceManager.GetString("Missing_chapter_number__0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing chapter numbers {0}-{1}.
        /// </summary>
        internal static string Missing_chapter_numbers__0___1_ {
            get {
                return ResourceManager.GetString("Missing_chapter_numbers__0___1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing continuation mark: level {0}.
        /// </summary>
        internal static string Missing_continuation_mark__level__0_ {
            get {
                return ResourceManager.GetString("Missing_continuation_mark__level__0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing continuation marks: levels 1-{0}.
        /// </summary>
        internal static string Missing_continuation_marks__levels_1__0_ {
            get {
                return ResourceManager.GetString("Missing_continuation_marks__levels_1__0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing verse number {0}.
        /// </summary>
        internal static string Missing_verse_number__0_ {
            get {
                return ResourceManager.GetString("Missing_verse_number__0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing verse numbers {0}-{1}.
        /// </summary>
        internal static string Missing_verse_numbers__0___1_ {
            get {
                return ResourceManager.GetString("Missing_verse_numbers__0___1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing verse text in verse {0}.
        /// </summary>
        internal static string Missing_verse_text_in_verse__0_ {
            get {
                return ResourceManager.GetString("Missing_verse_text_in_verse__0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overlapping pair.
        /// </summary>
        internal static string Overlapping_pair {
            get {
                return ResourceManager.GetString("Overlapping_pair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proper nouns should begin with a capital letter.
        /// </summary>
        internal static string Proper_nouns_should_begin_with_a_capital_letter {
            get {
                return ResourceManager.GetString("Proper_nouns_should_begin_with_a_capital_letter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeated word.
        /// </summary>
        internal static string Repeated_word {
            get {
                return ResourceManager.GetString("Repeated_word", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sentence should begin with a capital letter.
        /// </summary>
        internal static string Sentence_should_begin_with_a_capital_letter {
            get {
                return ResourceManager.GetString("Sentence_should_begin_with_a_capital_letter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space found in verse bridge.
        /// </summary>
        internal static string Space_found_in_verse_bridge {
            get {
                return ResourceManager.GetString("Space_found_in_verse_bridge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space found in verse number.
        /// </summary>
        internal static string Space_found_in_verse_number {
            get {
                return ResourceManager.GetString("Space_found_in_verse_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text in the {0} style should begin with a capital letter.
        /// </summary>
        internal static string Text_in_the__0__style_should_begin_with_a_capital_letter {
            get {
                return ResourceManager.GetString("Text_in_the__0__style_should_begin_with_a_capital_letter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title should begin with a capital letter.
        /// </summary>
        internal static string Title_should_begin_with_a_capital_letter {
            get {
                return ResourceManager.GetString("Title_should_begin_with_a_capital_letter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected opening mark: level {0}.
        /// </summary>
        internal static string Unexpected_opening_mark__level__0_ {
            get {
                return ResourceManager.GetString("Unexpected_opening_mark__level__0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected verse number.
        /// </summary>
        internal static string Unexpected_verse_number {
            get {
                return ResourceManager.GetString("Unexpected_verse_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected verse numbers.
        /// </summary>
        internal static string Unexpected_verse_numbers {
            get {
                return ResourceManager.GetString("Unexpected_verse_numbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unmatched closing mark: level {0}.
        /// </summary>
        internal static string Unmatched_closing_mark__level__0_ {
            get {
                return ResourceManager.GetString("Unmatched_closing_mark__level__0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unmatched opening mark: level {0}.
        /// </summary>
        internal static string Unmatched_opening_mark__level__0_ {
            get {
                return ResourceManager.GetString("Unmatched_opening_mark__level__0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unmatched punctuation.
        /// </summary>
        internal static string Unmatched_punctuation {
            get {
                return ResourceManager.GetString("Unmatched_punctuation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unspecified use of punctuation pattern.
        /// </summary>
        internal static string Unspecified_use_of_punctuation_pattern {
            get {
                return ResourceManager.GetString("Unspecified_use_of_punctuation_pattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verse number out of order.
        /// </summary>
        internal static string Verse_number_out_of_order {
            get {
                return ResourceManager.GetString("Verse_number_out_of_order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verse number out of order; expected verse {0}.
        /// </summary>
        internal static string Verse_number_out_of_order__expected_verse__0_ {
            get {
                return ResourceManager.GetString("Verse_number_out_of_order__expected_verse__0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verse number out of range.
        /// </summary>
        internal static string Verse_number_out_of_range {
            get {
                return ResourceManager.GetString("Verse_number_out_of_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verse numbers out of order.
        /// </summary>
        internal static string Verse_numbers_out_of_order {
            get {
                return ResourceManager.GetString("Verse_numbers_out_of_order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verse numbers out of range.
        /// </summary>
        internal static string Verse_numbers_out_of_range {
            get {
                return ResourceManager.GetString("Verse_numbers_out_of_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verses numbers out of order; expected verse {0}.
        /// </summary>
        internal static string Verses_numbers_out_of_order__expected_verse__0_ {
            get {
                return ResourceManager.GetString("Verses_numbers_out_of_order__expected_verse__0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word has mixed capitalization.
        /// </summary>
        internal static string Word_has_mixed_capitalization {
            get {
                return ResourceManager.GetString("Word_has_mixed_capitalization", resourceCulture);
            }
        }
    }
}
