//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIL.LCModel.FixData {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SIL.LCModel.FixData.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding ownerguid=&apos;{0}&apos; (class=&apos;{1}&apos;, guid=&apos;{2}&apos;)..
        /// </summary>
        public static string ksAddingLinkToOwner {
            get {
                return ResourceManager.GetString("ksAddingLinkToOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing default value type added to {0}.
        /// </summary>
        public static string ksAddingMissingDefaultForValueType {
            get {
                return ResourceManager.GetString("ksAddingMissingDefaultForValueType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjusted homograph number in {0} from {1} to {2}.
        /// </summary>
        public static string ksAdjustedHomograph {
            get {
                return ResourceManager.GetString("ksAdjustedHomograph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjusting reference to missing Segment by changing analysis object guid=&apos;{0}&apos;, class=&apos;{1}&apos;, field=&apos;{2}&apos;..
        /// </summary>
        public static string ksAdjustingAnalysisRefObj {
            get {
                return ResourceManager.GetString("ksAdjustingAnalysisRefObj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing ownerguid value from &apos;{0}&apos; to &apos;{1}&apos; (class=&apos;{2}&apos;, guid=&apos;{3}&apos;)..
        /// </summary>
        public static string ksChangingOwnerGuidValue {
            get {
                return ResourceManager.GetString("ksChangingOwnerGuidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wordform with guid &apos;{0}&apos; has same form ({1}) as &apos;{2}&apos; and was merged.
        /// </summary>
        public static string ksDuplicateWordform {
            get {
                return ResourceManager.GetString("ksDuplicateWordform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looking for and fixing errors in {0}.
        /// </summary>
        public static string ksLookingForAndFixingErrors {
            get {
                return ResourceManager.GetString("ksLookingForAndFixingErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object with guid &apos;{0}&apos; already exists! (not fixed).
        /// </summary>
        public static string ksObjectWithGuidAlreadyExists {
            get {
                return ResourceManager.GetString("ksObjectWithGuidAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object with guid &apos;{0}&apos; is already owned, so can&apos;t be owned by &apos;{1}&apos;.
        /// </summary>
        public static string ksObjectWithGuidAlreadyOwned {
            get {
                return ResourceManager.GetString("ksObjectWithGuidAlreadyOwned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading the input file {0}.
        /// </summary>
        public static string ksReadingTheInputFile {
            get {
                return ResourceManager.GetString("ksReadingTheInputFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing unused MorphoSyntaxAnalysis.
        /// </summary>
        public static string ksRemovedUnusedMsa {
            get {
                return ResourceManager.GetString("ksRemovedUnusedMsa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing reference to missing Segment by deleting analysis object guid=&apos;{0}&apos;, class=&apos;{1}&apos;, ownerguid=&apos;{2}&apos;..
        /// </summary>
        public static string ksRemovingBadAnalysisRefObj {
            get {
                return ResourceManager.GetString("ksRemovingBadAnalysisRefObj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing LexReference with too few references (Targets) (guid=&apos;{0}&apos;) from its owner (guid=&apos;{1}&apos;)..
        /// </summary>
        public static string ksRemovingBadLexReference {
            get {
                return ResourceManager.GetString("ksRemovingBadLexReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing dangling link to Form &apos;{0}&apos; for WfiMorphBundle &apos;{1}&apos;..
        /// </summary>
        public static string ksRemovingDanglingMorph {
            get {
                return ResourceManager.GetString("ksRemovingDanglingMorph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing dangling link to MSA &apos;{0}&apos; for WfiMorphBundle &apos;{1}&apos;..
        /// </summary>
        public static string ksRemovingDanglingMsa {
            get {
                return ResourceManager.GetString("ksRemovingDanglingMsa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed alternative {0} from {1} of {2} because it has the same writing system as {3}.
        /// </summary>
        public static string ksRemovingDuplicateAlternative {
            get {
                return ResourceManager.GetString("ksRemovingDuplicateAlternative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing duplicate style {0}..
        /// </summary>
        public static string ksRemovingDuplicateStyle {
            get {
                return ResourceManager.GetString("ksRemovingDuplicateStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing &apos;editable&apos; attribute from a string in a {0}.
        /// </summary>
        public static string ksRemovingEditableAttribute {
            get {
                return ResourceManager.GetString("ksRemovingEditableAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing invalid Generic Date {0} from {1} of {2} ({3})..
        /// </summary>
        public static string ksRemovingGenericDate {
            get {
                return ResourceManager.GetString("ksRemovingGenericDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing dangling link to &apos;{0}&apos; (class=&apos;{1}&apos;, guid=&apos;{2}&apos;, field=&apos;{3}&apos;)..
        /// </summary>
        public static string ksRemovingLinkToNonexistingObject {
            get {
                return ResourceManager.GetString("ksRemovingLinkToNonexistingObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing multiple ownership link &apos;{0}&apos; (class=&apos;{1}&apos;, guid=&apos;{2}&apos;, field=&apos;{3}&apos;)..
        /// </summary>
        public static string ksRemovingMultipleOwnershipLink {
            get {
                return ResourceManager.GetString("ksRemovingMultipleOwnershipLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing object with nonexistent owner (invalid ownerguid=&apos;{0}&apos;, class=&apos;{1}&apos;, guid=&apos;{2}&apos;)..
        /// </summary>
        public static string ksRemovingObjectWithBadOwner {
            get {
                return ResourceManager.GetString("ksRemovingObjectWithBadOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing owner of empty sequence (guid=&apos;{0}&apos; class=&apos;{1}&apos;) from its owner (guid=&apos;{2}&apos;)..
        /// </summary>
        public static string ksRemovingOwnerOfEmptySequence {
            get {
                return ResourceManager.GetString("ksRemovingOwnerOfEmptySequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing undefined custom property &apos;{0}&apos; from class=&apos;{1}&apos;, guid=&apos;{2}&apos;..
        /// </summary>
        public static string ksRemovingUndefinedCustomProperty {
            get {
                return ResourceManager.GetString("ksRemovingUndefinedCustomProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixing link to Form based on only Form of entry for WfiMorphBundle &apos;{0}&apos;..
        /// </summary>
        public static string ksRepairingBundleFormFromEntry {
            get {
                return ResourceManager.GetString("ksRepairingBundleFormFromEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repairing duplicate lists both named &quot;{0}&quot;. &quot;{1}&quot; kept the original name and &quot;{2}&quot;  was renamed to &quot;{3}&quot;.
        /// </summary>
        public static string ksRepairingDuplicateListName {
            get {
                return ResourceManager.GetString("ksRepairingDuplicateListName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixing link to MSA based on only MSA of entry for WfiMorphBundle &apos;{0}&apos;..
        /// </summary>
        public static string ksRepairingMorphBundleFromEntry {
            get {
                return ResourceManager.GetString("ksRepairingMorphBundleFromEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixing link to MSA based on Sense MSA (class=&apos;WfiMorphBundle&apos;, guid=&apos;{0}&apos;)..
        /// </summary>
        public static string ksRepairingMorphBundleFromSense {
            get {
                return ResourceManager.GetString("ksRepairingMorphBundleFromSense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This utility attempts to fix various errors in a FieldWorks project file.  The project must not be open, and must be in the fwdata (XML) format..
        /// </summary>
        public static string ksThisUtilityAttemptsTo {
            get {
                return ResourceManager.GetString("ksThisUtilityAttemptsTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing unused rt element. (class=&apos;{0}&apos;, guid=&apos;{1}&apos;)..
        /// </summary>
        public static string ksUnusedRtElement {
            get {
                return ResourceManager.GetString("ksUnusedRtElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this when a project is throwing exceptions such as &quot;Key 62c22e20-8d8a-42bf-a54c-e21529284f2d not found in identity map...&quot;, and you suspect the data has been corrupted somehow..
        /// </summary>
        public static string ksUseThisWhen {
            get {
                return ResourceManager.GetString("ksUseThisWhen", resourceCulture);
            }
        }
    }
}
