//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIL.LCModel.FixData {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("SIL.LCModel.FixData.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ksReadingTheInputFile {
            get {
                return ResourceManager.GetString("ksReadingTheInputFile", resourceCulture);
            }
        }
        
        internal static string ksLookingForAndFixingErrors {
            get {
                return ResourceManager.GetString("ksLookingForAndFixingErrors", resourceCulture);
            }
        }
        
        internal static string ksObjectWithGuidAlreadyExists {
            get {
                return ResourceManager.GetString("ksObjectWithGuidAlreadyExists", resourceCulture);
            }
        }
        
        internal static string ksObjectWithGuidAlreadyOwned {
            get {
                return ResourceManager.GetString("ksObjectWithGuidAlreadyOwned", resourceCulture);
            }
        }
        
        internal static string ksChangingOwnerGuidValue {
            get {
                return ResourceManager.GetString("ksChangingOwnerGuidValue", resourceCulture);
            }
        }
        
        internal static string ksRemovingObjectWithBadOwner {
            get {
                return ResourceManager.GetString("ksRemovingObjectWithBadOwner", resourceCulture);
            }
        }
        
        internal static string ksAddingLinkToOwner {
            get {
                return ResourceManager.GetString("ksAddingLinkToOwner", resourceCulture);
            }
        }
        
        internal static string ksRemovingLinkToNonexistingObject {
            get {
                return ResourceManager.GetString("ksRemovingLinkToNonexistingObject", resourceCulture);
            }
        }
        
        internal static string ksRemovingMultipleOwnershipLink {
            get {
                return ResourceManager.GetString("ksRemovingMultipleOwnershipLink", resourceCulture);
            }
        }
        
        internal static string ksUseThisWhen {
            get {
                return ResourceManager.GetString("ksUseThisWhen", resourceCulture);
            }
        }
        
        internal static string ksThisUtilityAttemptsTo {
            get {
                return ResourceManager.GetString("ksThisUtilityAttemptsTo", resourceCulture);
            }
        }
        
        internal static string ksRemovingEditableAttribute {
            get {
                return ResourceManager.GetString("ksRemovingEditableAttribute", resourceCulture);
            }
        }
        
        internal static string ksRemovingGenericDate {
            get {
                return ResourceManager.GetString("ksRemovingGenericDate", resourceCulture);
            }
        }
        
        internal static string ksRemovingDuplicateAlternative {
            get {
                return ResourceManager.GetString("ksRemovingDuplicateAlternative", resourceCulture);
            }
        }
        
        internal static string ksRemovingOwnerOfEmptySequence {
            get {
                return ResourceManager.GetString("ksRemovingOwnerOfEmptySequence", resourceCulture);
            }
        }
        
        internal static string ksAdjustingAnalysisRefObj {
            get {
                return ResourceManager.GetString("ksAdjustingAnalysisRefObj", resourceCulture);
            }
        }
        
        internal static string ksRemovingBadAnalysisRefObj {
            get {
                return ResourceManager.GetString("ksRemovingBadAnalysisRefObj", resourceCulture);
            }
        }
        
        internal static string ksDuplicateWordform {
            get {
                return ResourceManager.GetString("ksDuplicateWordform", resourceCulture);
            }
        }
        
        internal static string ksRemovingUndefinedCustomProperty {
            get {
                return ResourceManager.GetString("ksRemovingUndefinedCustomProperty", resourceCulture);
            }
        }
        
        internal static string ksAdjustedHomograph {
            get {
                return ResourceManager.GetString("ksAdjustedHomograph", resourceCulture);
            }
        }
        
        internal static string ksRemovedUnusedMsa {
            get {
                return ResourceManager.GetString("ksRemovedUnusedMsa", resourceCulture);
            }
        }
        
        internal static string ksRemovingDanglingMorph {
            get {
                return ResourceManager.GetString("ksRemovingDanglingMorph", resourceCulture);
            }
        }
        
        internal static string ksRemovingDanglingMsa {
            get {
                return ResourceManager.GetString("ksRemovingDanglingMsa", resourceCulture);
            }
        }
        
        internal static string ksRepairingBundleFormFromEntry {
            get {
                return ResourceManager.GetString("ksRepairingBundleFormFromEntry", resourceCulture);
            }
        }
        
        internal static string ksRepairingMorphBundleFromEntry {
            get {
                return ResourceManager.GetString("ksRepairingMorphBundleFromEntry", resourceCulture);
            }
        }
        
        internal static string ksRepairingMorphBundleFromSense {
            get {
                return ResourceManager.GetString("ksRepairingMorphBundleFromSense", resourceCulture);
            }
        }
        
        internal static string ksUnusedRtElement {
            get {
                return ResourceManager.GetString("ksUnusedRtElement", resourceCulture);
            }
        }
        
        internal static string ksAddingMissingDefaultForValueType {
            get {
                return ResourceManager.GetString("ksAddingMissingDefaultForValueType", resourceCulture);
            }
        }
        
        internal static string ksRepairingDuplicateListName {
            get {
                return ResourceManager.GetString("ksRepairingDuplicateListName", resourceCulture);
            }
        }
        
        internal static string ksRemovingBadLexReference {
            get {
                return ResourceManager.GetString("ksRemovingBadLexReference", resourceCulture);
            }
        }
        
        internal static string ksRemovingDuplicateStyle {
            get {
                return ResourceManager.GetString("ksRemovingDuplicateStyle", resourceCulture);
            }
        }
    }
}
