
name: LibLCM CI and CD

on:
  pull_request:
    branches: [ develop ]
  push:
    branches: [ develop ]

jobs:

  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    env:
      DOTNET_NOLOGO: true

    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Build
      run: dotnet build

    - name: Install NUnit.ConsoleRunner
      run: nuget install NUnit.ConsoleRunner -Version 3.13.0 -DirectDownload -OutputDirectory .

    - name: Collect Test Assemblies
      run: echo "TESTASSEMBLIES=$(find artifacts -type f -name *.Tests.dll | paste -sd ' ')" >> $GITHUB_ENV
      shell: bash

    - name: Run Tests
      run: ./NUnit.ConsoleRunner.3.13.0/tools/nunit3-console.exe  ${{ env.TESTASSEMBLIES }} -output testresults.txt
