name: Chorus .NET6

on:
  [push, pull_request, workflow_dispatch]

jobs:
  build_test_deploy:
    env:
      NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    runs-on: windows-latest
    permissions: write-all
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # fetch full history for GitVersion
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        source-url: https://nuget.pkg.github.com/sillsdev/index.json
    - name: Restore
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release src/SIL.LCModel/SIL.LCModel.csproj
    - name: Pack
      if: github.ref == 'refs/heads/migrationToDotNet6'
      run: dotnet pack -c Release
    #- name: Deploy
     # if: github.ref == 'refs/heads/migrationToDotNet6'
      #run: dotnet nuget push output/*.nupkg -s https://api.nuget.org/v3/index.json -k ${{secrets.SILLSDEV_PUBLISH_NUGET_ORG}} --skip-duplicate
